#!/usr/bin/ruby

require 'digest/sha1'

file = "background_app/.hash"
hash = 0

begin
  hash = File.read(file)
rescue SystemCallError
	r = Random.new

	hash = Digest::SHA1.hexdigest r.rand().to_s
  File.write(file, hash)
end

puts "[HASH] : Add Hash identity: " + hash

system "open http://sheffield.spina.me/entryByHash/" + hash + " > /dev/null"

system "cd background_app/ && node index.js"


